### ISSUE TITLE
Ein paar Anmerkungen

### ISSUE THREAD

**Issue by roessling** [felixsinger/examnotices#1]
Ein paar Anmerkungen :-)

- Seite 1: _new_ Integer.valueOf(5) => nur Integer.valueOf(5), auf keinen Fall ein "new" davor! (Analog bei Double)
- Seite 1: _asList_ erwartet kein Array, sondern einfach eine Aufzählung von Elementen: List l = Arrays.asList(1, 2, 3);
- Seite 3ff Datentypen: hier wäre es hilfreicher, statt _Object getFirst()_ in einer _LinkedList_ gleich eine _LinkedList_**<E>** mit dann **E** _getFirst()_ (analog für get, getLast, remove, set und Stream<E> stream()) zu nutzen. Für die anderen Datentypen (HashMap) analog.
- Seite 6: _foreach_ heißt korrekt _for**E**each__ (2x)
- Seite 6: "Racket" sollte "HtDP-TL" heißen. __Racket__ gibt es auch, unterscheidet sich aber in (kleinen, aber gemeinen und potenziell "Klausurpunkte kostenden") Details (andere Funktionen etc.)

**Comment by felixsinger** [comment]
Vielen Dank :)

**Comment by roessling** [comment]
Danke für die schnellen Anpassungen, Felix :-)
